version: 1.0.{build}

clone_folder: c:\dev\soundex

build_script:
  - cd c:\dev\soundex
  - md build
  - cd build
  - cmake -DCMAKE_CXX_FLAGS:STRING="/W4" -G"Visual Studio 12" ..
  - msbuild /m /p:Configuration=Release /p:Platform="Win32" Soundex.sln

test_script:
  - cd c:\dev\soundex\build
  - cmd: ctest -VV -C Release
  - cd lib
  - cmd: SoundexUnitTests.exe --gtest_output=xml
  - ps: >-
    # upload results to AppVeyor

    $wc = New-Object 'System.Net.WebClient'

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\xunit-results.xml))
